// Export pages
export '/pages/auth/splash_page/splash_page_widget.dart' show SplashPageWidget;
export '/pages/auth/choose_auth_page/choose_auth_page_widget.dart'
    show ChooseAuthPageWidget;
export '/pages/auth/login/choose_login_page/choose_login_page_widget.dart'
    show ChooseLoginPageWidget;
export '/pages/auth/login/login_page/login_page_widget.dart'
    show LoginPageWidget;
export '/onboard_page_page/onboard_page_page_widget.dart'
    show OnboardPagePageWidget;
export '/pages/vendor/vendor_dashboard_page/vendor_dashboard_page_widget.dart'
    show VendorDashboardPageWidget;
export '/pages/auth/sign_up_flow/choose_register_page/choose_register_page_widget.dart'
    show ChooseRegisterPageWidget;
export '/pages/auth/sign_up_flow/sign_up_page/sign_up_page_widget.dart'
    show SignUpPageWidget;
export '/create_account5/create_account5_widget.dart' show CreateAccount5Widget;
export '/pages/auth/sign_up_flow/terms_agreement_page/terms_agreement_page_widget.dart'
    show TermsAgreementPageWidget;
export '/pages/vendor/add_product_page_one/add_product_page_one_widget.dart'
    show AddProductPageOneWidget;
export '/pages/vendor/vendor_likes_page/vendor_likes_page_widget.dart'
    show VendorLikesPageWidget;
export '/pages/vendor/vendor_cart_page/vendor_cart_page_widget.dart'
    show VendorCartPageWidget;
export '/pages/home/home_page/home_page_widget.dart' show HomePageWidget;
export '/pages/product_pages/single_product_page/single_product_page_widget.dart'
    show SingleProductPageWidget;
export '/pages/vendor/add_product_page_two/add_product_page_two_widget.dart'
    show AddProductPageTwoWidget;
export '/pages/vendor/services/add_service_page_one/add_service_page_one_widget.dart'
    show AddServicePageOneWidget;
export '/pages/vendor/services/add_servcie_page_two/add_servcie_page_two_widget.dart'
    show AddServciePageTwoWidget;
export '/pages/vendor/product_boost_page/product_boost_page_widget.dart'
    show ProductBoostPageWidget;
export '/pages/vendor/services/service_dashboard/service_dashboard_widget.dart'
    show ServiceDashboardWidget;
export '/pages/vendor/services/search_client_page/search_client_page_widget.dart'
    show SearchClientPageWidget;
export '/pages/vendor/services/project_request_view_page/project_request_view_page_widget.dart'
    show ProjectRequestViewPageWidget;
export '/pages/vendor/services/project_reject_page/project_reject_page_widget.dart'
    show ProjectRejectPageWidget;
export '/pages/vendor/services/create_fixed_project_page/create_fixed_project_page_widget.dart'
    show CreateFixedProjectPageWidget;
export '/pages/vendor/services/create_hourly_project_page/create_hourly_project_page_widget.dart'
    show CreateHourlyProjectPageWidget;
export '/pages/vendor/services/fixed_project_detail_page/fixed_project_detail_page_widget.dart'
    show FixedProjectDetailPageWidget;
export '/pages/vendor/services/project_end_confirm_page/project_end_confirm_page_widget.dart'
    show ProjectEndConfirmPageWidget;
